### PR TITLE
New tool: ImSpectR

### PR DESCRIPTION
**Pull request by sbwilson91**
New tool: ImSpectR

With this package .fsa intensity files or files with sequencing lengths representing the CDR3 region of T-cell receptors can be loaded, visualized and scored for quantification of the immune repertoire.

If your pull request if related to a tool entry please make sure you have
followed the instructions in the wiki (and thank you for contributing!).

Other contributions are more than welcome, just let us know what you
have done below!

### CODE REVIEW

**Comment by lazappi** [comment]
These descriptions might be a bit long for Twitter but I'll merge them and we'll see how it goes.

**Comment by lazappi** [comment]
Ok. Message length was fine but you missed the link on ImSpectR and somehow the comment made it into the other commit. Really minor though and this seems to be working smoother now 😺.

**Comment by sbwilson91** [comment]
I've not figured out how to use your preset commit message which is
probably part of the problem. It's the vim editor isn't it? I've always
used nano so unfamiliar with the commands. How do I get it to commit that
message?

**Comment by lazappi** [comment]
Ahhh...I see. It should be opening the default editor which is probably set to vim. Try running `git config --global core.editor "nano"` and hopefully it will open nano next time. If that doesn't work you might need to add the following lines to your `~/.bashrc` file to set the default editor for everything (not just git).

```bash
export EDITOR=nano
export VISUAL="$EDITOR"
```

**Pull request merged**
