### PR TITLE
Updated AltAnalyze description and details

### PR DESCRIPTION
**Pull request by nsalomonis**
Updated AltAnalyze software description, software features for single-cell analysis ("Quantification", "Normalisation", "QualityControl", "GeneFiltering", "Clustering", "Classification", "DifferentialExpression", "MarkerGenes", "ExpressionPatterns", "GeneSets", "GeneNetworks", "CellCycle", "DimensionalityReduction", "AlternativeSplicing", "Visualisation", "Interactive"), and number of citations with verified software references (https://docs.google.com/spreadsheets/d/16td2Gj58eHSaogNfAopAZpAMM4s6hZWTSj1zXEPTy0o/edit#gid=0),

### CODE REVIEW

**Comment by nsalomonis** [comment]
Updated the description, features and citations for AltAnalyze in the json data description file (see associated comments).

**Comment by lazappi** [comment]
Hi @nsalomonis 

Thanks for the update. I use single_cell_software.csv as the source file and the JSON files are generated automatically (by process_csv.R) which gets the number of citations (from Crossref) among other things. I should probably write this somewhere so that it is clear. Can you please make your changes to the CSV file and run the script to generate the JSON? If you don't have time I can do it from what you have done here.

Sorry for the confusion

Luke

**Comment by nsalomonis** [comment]
Hi Luke,

If OK, could you generate from the attached CSV? Thanks!

Nathan

**Comment by lazappi** [comment]
Hi Nathan

I would be happy to do that but I can't find the CSV, I think maybe it didn't make it through your email reply? Could you try uploading it to the pull request of the website? I think you should just be able to drag it into the text box.

Luke

**Comment by nsalomonis** [comment]
Hey Luke,

That makes sense that Github would block attachments. I just committed that
file change. Thanks again!
Best,
Nathan

**Pull request closed without merging**
